" .gvimrc

" options {{{1
" vim options {{{2
set mousehide

" font options {{{2
if g:vimrc.is_win
  set guifont=M+_1m:h9
  if has('directx')
    set renderoptions=type:directx,renmode:5
  endif
else
  set guifont=M+\ 1m\ 11
endif

" window options {{{2
set columns=100
set lines=30
set guioptions+=!
set guioptions-=T
if has('patch-8.0.1278')
  set guioptions+=k
endif

" ime options {{{2
if has('multi_byte_ime')
  " change cursor color when IME is on
  highlight CursorIM guibg=#ee5c42

  set iminsert=0
  set imsearch=0
endif

" mappings {{{1
map  <S-Insert> <MiddleMouse>
map! <S-Insert> <MiddleMouse>
